### PR TITLE
rm non-existing guide

### PR DESCRIPTION
**Pull request by htor**
... and provide full link to all docs for clarity

### CODE REVIEW

**Comment by crucialfelix** [comment]
Both of these links work for me:

[API](https://crucialfelix.github.io/supercolliderjs/api/)	

[Guide](https://crucialfelix.gitbooks.io/supercollider-js-guide/content/)

Though they are also linked to from this page:
https://crucialfelix.github.io/supercolliderjs

There is a new release coming soon and that will mean updating documentation, guides and examples.

**Comment by htor** [comment]
ah, sorry thought the guide link was just dead!

**Comment by crucialfelix** [comment]
The guide certainly needs to be updated and finished! 

Thanks for submitting a PR anyway. Help is always appreciated!

**Comment by crucialfelix** [comment]
I now realize why the link looks broken. Because they are one line: "API Guide"

It's supposed to be:

API
Guide

**Pull request closed without merging**
